import os
import glob
import numpy as np
from hdmf_zarr import NWBZarrIO
from pynwb import NWBHDF5IO
from utils import get_fitted_model_names, get_fitted_latent
from aind_dynamic_foraging_basic_analysis.plot import plot_foraging_session
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import pandas as pd
from scipy.cluster.hierarchy import linkage, dendrogram
from scipy.ndimage import gaussian_filter1d
from aind_spurious_correlation import methods
from shared import Shared
from typing import Optional, Any, Tuple
from scipy.optimize import minimize
import statsmodels.api as sm

class ModelFitting(Shared):
    def __init__(self, session_name: str = None, folder_path: str = '/root/capsule/data/'):
        """
        Initializes the ModelFitting instance for reading NWB behavior data and fitting a Q-learning model.

        Parameters:
            session_name (str): The session name of the NWB file (e.g., '764791_2025-01-15_13-08-58').
            folder_path (str): The folder path where the NWB files are stored (default is '/root/capsule/data/').
        """
        self.session_name = session_name
        self.folder_path = folder_path
        self.nwb_behavior_data = None
        self.fitted_model_names = None
        self.internal_fitted_model_names = {}  # Dictionary to hold fitted results keyed by model name.
        self.fitted_latent = {}
        self.choice_regression_result = None

    def fit_q_learning_model(self, model_name: str = "q_learning_Y1") -> Optional[dict]:
        """
        Fits a Q-learning model to behavioral data from a two-choice task.
        
        In this model:
          - For each trial, two action values Ql and Qr are maintained.
          - If the animal chooses left (encoded as 0), the left Q-value is updated:
                Ql(t+1) = Ql(t) + α₊ [R(t) - Ql(t)]   if δ(t) ≥ 0
                         = Ql(t) + α₋ [R(t) - Ql(t)]   if δ(t) <  0
            and the unchosen (right) value decays:
                Qr(t+1) = ζ · Qr(t)
          - If the animal chooses right (encoded as 1), the right Q-value is updated analogously,
            and the left value decays.
          - The choice probabilities are generated by a softmax function:
                P(c(t)=r) = 1 / (1 + exp(-[β*(Qr(t)-Ql(t)) + bias]))
                P(c(t)=l) = 1 - P(c(t)=r)
                
        The function computes the negative log-likelihood of the observed choices under this model and uses 
        an optimizer to fit the free parameters: α₊, α₋, ζ, β, and bias.
        
        After fitting the model, it simulates the behavior using the fitted parameters to compute:
          - The predicted right choice probability on each trial.
          - The trial-by-trial Q-values for the left (Ql) and right (Qr) options.
          - The predicted left choice probability is computed as 1 minus the predicted right choice probability.
        
        The fitted parameters (with names), predicted right and left choice probabilities, and Q-values are saved 
        to the instance under the key corresponding to the provided model name.
        
        Parameters:
            model_name (str): A name to assign to this model fit (default "q_learning_x1").
        
        Returns:
            A dictionary containing:
                - 'fitted_params': A dictionary mapping parameter names to their fitted values.
                - 'neg_log_likelihood': The negative log-likelihood value at the optimum.
                - 'predicted_right_choice_probabilities': An array of predicted right choice probabilities per trial.
                - 'predicted_left_choice_probabilities': An array of predicted left choice probabilities per trial.
                - 'ql_values': An array of Ql values (left Q-values) per trial.
                - 'qr_values': An array of Qr values (right Q-values) per trial.
                - 'success': A boolean flag indicating whether the optimization succeeded.
            If optimization fails, returns None.
        
        Assumes that self.nwb_behavior_data is already loaded and contains the following fields:
            - trials['animal_response']: 0 for left, 1 for right, 2 for no response.
            - trials['rewarded_historyL']: Boolean (or 0/1) for reward delivered on left.
            - trials['rewarded_historyR']: Boolean (or 0/1) for reward delivered on right.
        """
        # Extract behavioral data from the NWB structure.
        if hasattr(self,'nwb_behavior_data'):
            nwb_data=self.nwb_behavior_data
        elif hasattr(self,'nwb_ophys_data'):
            nwb_data=self.nwb_ophys_data
        else:
            print('No behavior NWB found!')
            return

        animal_response = nwb_data.trials['animal_response'][:]  # 0: left, 1: right, 2: no response
        reward_left = nwb_data.trials['rewarded_historyL'][:]       # Boolean or 0/1 for left reward
        reward_right = nwb_data.trials['rewarded_historyR'][:]      # Boolean or 0/1 for right reward

        # Convert to numpy arrays and remove trials with no response (coded as 2).
        animal_response = np.array(animal_response)
        reward_left = np.array(reward_left).astype(float)
        reward_right = np.array(reward_right).astype(float)
        
        valid_trials = animal_response != 2
        animal_response = animal_response[valid_trials]
        reward_left = reward_left[valid_trials]
        reward_right = reward_right[valid_trials]

        n_trials = len(animal_response)

        def neg_log_likelihood(params: np.ndarray) -> float:
            """
            Compute the negative log-likelihood of the observed choices under the Q-learning model.
            
            Parameters:
                params (np.ndarray): Parameter vector [α₊, α₋, ζ, β, bias].
            
            Returns:
                float: The negative log-likelihood.
            """
            alpha_pos, alpha_neg, zeta, beta, bias = params
            
            # Initialize Q-values (assuming initial Q-values are 0)
            Ql = 0
            Qr = 0
            log_lik = 0.0
            
            for t in range(n_trials):
                epsilon = 1e-10  # small constant to avoid log(0)
                p_right = 1.0 / (1.0 + np.exp(- (beta * (Qr - Ql) + bias)))
                
                if animal_response[t] == 1:  # right choice
                    log_lik += np.log(p_right + epsilon)
                elif animal_response[t] == 0:  # left choice
                    log_lik += np.log(1.0 - p_right + epsilon)
                
                # Update Q-values based on the chosen action.
                if animal_response[t] == 0:  # left chosen
                    R = reward_left[t]
                    delta = R - Ql
                    if delta >= 0:
                        Ql = Ql + alpha_pos * delta
                    else:
                        Ql = Ql + alpha_neg * delta
                    Qr = zeta * Qr
                elif animal_response[t] == 1:  # right chosen
                    R = reward_right[t]
                    delta = R - Qr
                    if delta >= 0:
                        Qr = Qr + alpha_pos * delta
                    else:
                        Qr = Qr + alpha_neg * delta
                    Ql = zeta * Ql
            return -log_lik

        # Initial parameter guesses: [α₊, α₋, ζ, β, bias]
        init_params = np.array([0.1, 0.1, 0.9, 5.0, 0.0])
        # Parameter bounds: α in [0,1], ζ in [0,1], β positive, bias unconstrained.
        bounds = [(0, 1), (0, 1), (0, 1), (1e-3, 100), (-10, 10)]
        
        result = minimize(neg_log_likelihood, init_params, bounds=bounds, method='L-BFGS-B')
        #result = minimize(neg_log_likelihood, init_params, method='Nelder-Mead') 
        if result.success:
            fitted_array = result.x
            # Map parameter names to the fitted values.
            param_names = ['alpha_pos', 'alpha_neg', 'zeta', 'beta', 'bias']
            fitted_params = dict(zip(param_names, fitted_array))
            print("Fitted parameters:")
            for name, value in fitted_params.items():
                print(f"  {name}: {value}")

            # Simulate the model with the fitted parameters to compute predicted right choice probabilities,
            # and store trial-by-trial Q-values.
            alpha_pos = fitted_params['alpha_pos']
            alpha_neg = fitted_params['alpha_neg']
            zeta = fitted_params['zeta']
            beta = fitted_params['beta']
            bias = fitted_params['bias']
            
            pred_p_right = np.zeros(n_trials)
            ql_vals = np.zeros(n_trials)
            qr_vals = np.zeros(n_trials)
            Ql = 0.0
            Qr = 0.0
            for t in range(n_trials):
                # Compute predicted right choice probability at the start of trial t.
                p_right = 1.0 / (1.0 + np.exp(- (beta * (Qr - Ql) + bias)))
                pred_p_right[t] = p_right

                # Update Q-values based on the observed choice.
                if animal_response[t] == 0:  # left chosen
                    R = reward_left[t]
                    delta = R - Ql
                    if delta >= 0:
                        Ql = Ql + alpha_pos * delta
                    else:
                        Ql = Ql + alpha_neg * delta
                    Qr = zeta * Qr
                elif animal_response[t] == 1:  # right chosen
                    R = reward_right[t]
                    delta = R - Qr
                    if delta >= 0:
                        Qr = Qr + alpha_pos * delta
                    else:
                        Qr = Qr + alpha_neg * delta
                    Ql = zeta * Ql

                # Save the updated Q-values for this trial.
                ql_vals[t] = Ql
                qr_vals[t] = Qr

            # keep conistent with Han's fitting
            ql_vals = np.insert(ql_vals, 0, 0)
            qr_vals = np.insert(qr_vals, 0, 0)

            # Compute predicted left choice probability as 1 - pred_p_right.
            pred_p_left = 1.0 - pred_p_right

            # Save the fitted model data into the internal dictionary.
            self.internal_fitted_model_names[model_name] = {
                'fitted_params': fitted_params,
                'neg_log_likelihood': result.fun,
                'fitted_latent_variables': {
                    'q_value': [ql_vals, qr_vals],         # q_value[0] contains left Q-values; q_value[1] contains right Q-values.
                    'choice_prob': [pred_p_left, pred_p_right]  # choice_prob[0] for left, choice_prob[1] for right.
                },
                'ql_values': ql_vals,
                'qr_values': qr_vals,
                'success': True
            }
            # Update fitted model names and latent variables.
            self.get_fitted_model_names()
            self.get_fitted_latent()
            return self.internal_fitted_model_names[model_name]
        else:
            print("Optimization failed:", result.message)
            return None

    def fit_choice_logistic_regression(self, lag: int = 10, folder_with_nwb: Optional[str] = None):
        """
        Fits the 2-parameter logistic regression model:
        logit(P(cr(t)=1)) = β0
                            + sum_{i=1 to lag} [β^R_i * (Rr(t-i) - Rl(t-i))]
                            + sum_{i=1 to lag} [β^NR_i * (Nr(t-i) - Nl(t-i))]
        where R=1 for rewarded choice, 0 otherwise,
            N=1 for unrewarded choice, 0 otherwise,
            r=1 for right, l=1 for left, etc.

        Ignores trials with no response (2).
        Saves the regression result in self.choice_regression_result.
        Also stores a dictionary in self.internal_fitted_model_names['logistic_regression'] with:
        - fit_result
        - model_summary
        - fitted_latent_variables['choice_prob']: [pred_p_left, pred_p_right]
        - used_trial_indices

        If folder_with_nwb is provided, we read ALL NWB files in that folder, accumulate the design matrix X and 
        outcome vector y from each, then do a SINGLE combined logistic regression on the appended data.

        Parameters:
        -----------
        lag : int
            Number of past trials used to form the regressors.
        folder_with_nwb : Optional[str]
            If provided, we gather all *.nwb files in that folder, read them one by one, 
            build a single combined dataset, then fit logistic regression to that combined set.
            If not provided, we fallback to reading from self.nwb_behavior_data (or self.nwb_ophys_data).

        Returns:
        --------
        result : statsmodels LogitResults or None
            The fitted logistic regression result, or None if something went wrong.
        """

        def _extract_X_y_from_nwb(nwb_data, lag):
            """
            Helper to extract design matrix X, outcome y, and used_trial_indices from a single NWB.
            Returns (X, y, used_trial_indices), each as a numpy array.
            Returns (None, None, None) if nwb_data is invalid or if no valid trials.
            """

            animal_response = np.array(nwb_data.trials['animal_response'][:])  # 0=left, 1=right, 2=no response
            reward_left = np.array(nwb_data.trials['rewarded_historyL'][:]).astype(float)
            reward_right = np.array(nwb_data.trials['rewarded_historyR'][:]).astype(float)

            n_trials = len(animal_response)
            if n_trials <= lag:
                print("Not enough trials to form regression with the given lag.")
                return None, None, None

            # Rr(t), Rl(t), Nr(t), Nl(t)
            Rr = np.zeros(n_trials, dtype=int)
            Rl = np.zeros(n_trials, dtype=int)
            Nr = np.zeros(n_trials, dtype=int)
            Nl = np.zeros(n_trials, dtype=int)
            for t in range(n_trials):
                if animal_response[t] == 0:  # left
                    if reward_left[t] == 1:
                        Rl[t] = 1
                    else:
                        Nl[t] = 1
                elif animal_response[t] == 1:  # right
                    if reward_right[t] == 1:
                        Rr[t] = 1
                    else:
                        Nr[t] = 1
                # if 2 => no response => skip

            X_rows = []
            y_list = []
            used_trial_indices = []
            for t in range(lag, n_trials):
                if animal_response[t] not in [0, 1]:
                    continue
                row = []
                # For i in 1..lag, rewarded difference
                for i in range(1, lag+1):
                    row.append(Rr[t-i] - Rl[t-i])
                # For i in 1..lag, unrewarded difference
                for i in range(1, lag+1):
                    row.append(Nr[t-i] - Nl[t-i])

                X_rows.append(row)
                y_list.append(animal_response[t])  # 0=left, 1=right
                used_trial_indices.append(t)

            if len(X_rows) == 0:
                print("No valid trials found for logistic regression in this NWB.")
                return None, None, None

            X_ = np.array(X_rows, dtype=float)
            y_ = np.array(y_list, dtype=int)
            used_idx = np.array(used_trial_indices, dtype=int)

            return X_, y_, used_idx

        # If a folder is provided, accumulate from many NWB files
        if folder_with_nwb is not None and os.path.isdir(folder_with_nwb):
            all_nwb_files = sorted(glob.glob(os.path.join(folder_with_nwb, '*.nwb')))
            if not all_nwb_files:
                print(f"No NWB files found in folder: {folder_with_nwb}")
                return None

            # Accumulate data from each NWB
            all_X = []
            all_y = []
            all_used_trials = []
            trial_offset = 0  # keep track of offset in indexing if we want unique used_trial_indices

            for nwb_file in all_nwb_files:
                print(f"Reading NWB: {nwb_file}")
                # read the NWB
                nwb_data = self.read_behavior_nwb(nwb_full_path=nwb_file)
                if nwb_data is None:
                    continue
                X_, y_, used_idx = _extract_X_y_from_nwb(nwb_data, lag)
                if X_ is None:
                    continue
                all_X.append(X_)
                all_y.append(y_)
                # shift used_idx by trial_offset so we have unique indices overall
                used_idx_shifted = used_idx + trial_offset
                all_used_trials.append(used_idx_shifted)
                # Next offset
                trial_offset += len(nwb_data.trials['animal_response'][:])  # total # of trials in this NWB

            if not all_X:
                print("No valid X data accumulated from any NWB in the folder.")
                return None

            X = np.vstack(all_X)  # combine all
            y = np.concatenate(all_y)
            used_trial_indices = np.concatenate(all_used_trials)

        else:
            # Fallback: use self.nwb_behavior_data if it exists
            if hasattr(self, 'nwb_behavior_data') and self.nwb_behavior_data is not None:
                nwb_data = self.nwb_behavior_data
            elif hasattr(self, 'nwb_ophys_data') and self.nwb_ophys_data is not None:
                nwb_data = self.nwb_ophys_data
            else:
                print('No behavior NWB found in self. Provide a folder_with_nwb instead.')
                return None

            X, y, used_trial_indices = _extract_X_y_from_nwb(nwb_data, lag)
            if X is None:
                return None

        # 5) Add intercept
        X_const = sm.add_constant(X)

        # 6) Fit the model
        try:
            logit_model = sm.Logit(y, X_const)
            result = logit_model.fit(disp=False)
        except Exception as e:
            print("Error during logistic regression fitting:", e)
            return None

        print(result.summary())
        self.choice_regression_result = result

        # 7) Compute predicted probabilities
        pred_p_right = result.predict(X_const)
        pred_p_left = 1 - pred_p_right

        # 8) Save logistic regression results
        self.internal_fitted_model_names['logistic_regression'] = {
            'fit_result': result,
            'model_summary': result.summary().as_text(),
            'fitted_latent_variables': {
                'choice_prob': [pred_p_left, pred_p_right]
            },
            'used_trial_indices': used_trial_indices
        }
        self.get_fitted_model_names()
        self.get_fitted_latent()
        
        return result


    def visualize_choice_logistic_regression(self, 
                                            lag: int = 10,                    
                                            title_font_size: int = 16,
                                            label_font_size: int = 12
                    ) -> None:
        """
        Visualizes the 2-parameter logistic regression model from fit_choice_logistic_regression.

        - Plots the intercept (bias) as a bar with confidence intervals at x=0.
        - Plots the rewarded (x1..x10) and unrewarded (x11..x20) coefficients as lines with confidence intervals,
        both sharing the same x-locations (1..10).
        - Displays a legend for intercept, rewarded, and unrewarded.
        - Also shows a separate plot comparing predicted probability vs. actual choices.
        """
        if self.choice_regression_result is None:
            print("No logistic regression result to visualize. Run fit_choice_logistic_regression first.")
            return

        # -- Extract regression coefficients and confidence intervals
        result = self.choice_regression_result
        params = result.params        # numpy array (length = 1 + 2*lag)
        conf_int = result.conf_int()  # shape: (1+2*lag, 2) => [lower, upper] per coefficient

        # If needed, define parameter names (optional).
        # We'll focus on numeric indexing here.
        # param_names = ['const'] + [f'x_{i}' for i in range(1, len(params))]

        # Confidence interval half-width for each coefficient
        ci_halfwidth = (conf_int[:, 1] - conf_int[:, 0]) / 2.0

        # -- 1) Intercept (bias)
        intercept = params[0]
        intercept_ci = ci_halfwidth[0]

        # -- 2) Rewarded and Unrewarded Coefficients
        # Rewarded: x1..x10 => indices [1..lag]
        rewarded_coeffs = params[1 : lag+1]
        rewarded_ci = ci_halfwidth[1 : lag+1]

        # Unrewarded: x11..x20 => indices [lag+1 .. 2*lag]
        unrewarded_coeffs = params[lag+1 : 2*lag+1]
        unrewarded_ci = ci_halfwidth[lag+1 : 2*lag+1]

        # X-values for rewarded/unrewarded: 1..10
        x_vals = np.arange(1, lag+1)

        fig, ax = plt.subplots(figsize=(10, 6))

        # -- Plot intercept as a bar at x=0
        bar_width = 0.4
        bar_color = 'lightblue'
        rects = ax.bar(0, intercept, width=bar_width, color=bar_color,
                    edgecolor='black', label='Intercept')
        # Error bar for intercept
        ax.errorbar(0, intercept, yerr=intercept_ci, fmt='none', ecolor='black', capsize=4)

        # -- Plot rewarded coefficients as a line with error bars
        # We'll use errorbar, which plots both the line (connecting points) and the error bars.
        ax.errorbar(x_vals,
                    rewarded_coeffs,
                    yerr=rewarded_ci,
                    fmt='-o',  # line + circle markers
                    color='blue',
                    ecolor='blue',
                    elinewidth=2,
                    capsize=4,
                    label='Rewarded')

        # -- Plot unrewarded coefficients as a line with error bars
        ax.errorbar(x_vals,
                    unrewarded_coeffs,
                    yerr=unrewarded_ci,
                    fmt='-o',  # line + circle markers
                    color='red',
                    ecolor='red',
                    elinewidth=2,
                    capsize=4,
                    label='Unrewarded')

        # -- X-axis setup
        # We'll have ticks from 0..10, where 0 is intercept, 1..10 is the lags
        ax.set_xticks(np.arange(0, lag+1))
        tick_labels = ['0'] + [str(i) for i in range(1, lag+1)]
        ax.set_xticklabels(tick_labels)
        ax.set_xlabel("Lag (Choice) [0=Intercept]", fontsize=label_font_size)

        # -- Labels, legend, and title
        ax.set_ylabel("Coefficient Value", fontsize=label_font_size)
        ax.set_title("Logistic Regression Coefficients with 95% CI", fontsize=title_font_size)
        ax.legend()  # show the legend for intercept, rewarded, and unrewarded

        plt.tight_layout()
        plt.show()

        # -- Predicted probability vs. actual choices
        pred_p_right = result.predict()  # shape: #rows in X
        # If we stored used_trial_indices, we can plot them in the correct absolute order
        used_indices = self.internal_fitted_model_names['logistic_regression'].get('used_trial_indices', None)
        if used_indices is not None:
            x_axis = used_indices
        else:
            # fallback: just use 0..n
            x_axis = np.arange(len(pred_p_right))

        fig, ax = plt.subplots(figsize=(10, 5))
        ax.plot(x_axis, pred_p_right, label='Predicted P(Right)', color='blue', marker='o', alpha=0.7)
        # We also have the actual binary choices in y
        # result.model.endog => the dependent variable from statsmodels
        actual_choices = result.model.endog
        ax.scatter(x_axis, actual_choices, color='red', label='Actual Choice (0=Left,1=Right)', alpha=0.5)
        ax.set_xlabel("Trial Index (Used in Regression)")
        ax.set_ylabel("Probability / Choice")
        ax.set_title("Predicted Probability vs. Actual Choice")
        ax.legend()
        plt.tight_layout()
        plt.show()

